import React, { useState, useEffect } from 'react';
import { getAlerts, acknowledgeAlert } from '../services/alertsService';
import { Badge } from '../components/common/Badge';
import { Button } from '../components/common/Button';
import { Bell, AlertTriangle, AlertCircle, Info, CheckCircle2, Trash2, Filter } from 'lucide-react';
import { useToast } from '../hooks/useToast';

export function AlertsPage({ onNavigate }) {
  const [alerts, setAlerts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState('ALL');
  const { addToast } = useToast();

  useEffect(() => {
    async function load() {
      setLoading(true);
      const res = await getAlerts();
      setAlerts(res);
      setLoading(false);
    }
    load();
  }, []);

  const handleAcknowledge = async (id) => {
    await acknowledgeAlert(id);
    setAlerts((prev) =>
      prev.map((a) => (a.id === id ? { ...a, acknowledged: true } : a))
    );
    addToast({ title: 'Alert Acknowledged', message: `Alert ${id} marked as acknowledged.`, type: 'success' });
  };

  const handleDismiss = (id) => {
    setAlerts((prev) => prev.filter((a) => a.id !== id));
    addToast({ title: 'Alert Dismissed', message: `Alert ${id} removed from feed.`, type: 'info' });
  };

  const filteredAlerts = alerts.filter((a) => {
    if (activeTab === 'ALL') return true;
    return a.severity.toUpperCase() === activeTab.toUpperCase();
  });

  if (loading) {
    return <div className="p-8 text-slate-400 animate-pulse">Loading AI Alerts stream...</div>;
  }

  return (
    <div className="p-4 lg:p-8 space-y-6 max-w-7xl mx-auto">
      {/* Title & Tabs */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-2xl font-extrabold text-slate-900 tracking-tight">Alerts & AI Recommendations</h2>
          <p className="text-xs text-slate-500 mt-1">
            Consolidated decision support recommendations generated by AI intelligence models.
          </p>
        </div>

        {/* Category Tabs */}
        <div className="flex items-center gap-2 bg-slate-100 p-1 rounded-xl">
          {['ALL', 'CRITICAL', 'WARNING', 'INFO'].map((tab) => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={`px-3 py-1.5 rounded-lg text-xs font-semibold transition-colors ${
                activeTab === tab
                  ? 'bg-[#0b2545] text-white shadow-xs'
                  : 'text-slate-600 hover:text-slate-900'
              }`}
            >
              {tab}
            </button>
          ))}
        </div>
      </div>

      {/* Alerts Cards List */}
      <div className="space-y-4">
        {filteredAlerts.length === 0 ? (
          <div className="p-12 text-center bg-white rounded-xl border border-slate-200 text-slate-500 text-xs">
            No alerts found under this category.
          </div>
        ) : (
          filteredAlerts.map((alert) => {
            const isCritical = alert.severity === 'critical';
            const isWarning = alert.severity === 'warning';
            const Icon = isCritical ? AlertCircle : isWarning ? AlertTriangle : Info;

            return (
              <div
                key={alert.id}
                className={`p-5 rounded-xl border bg-white shadow-2xs transition-all duration-200 ${
                  isCritical
                    ? 'border-red-200'
                    : isWarning
                    ? 'border-amber-200'
                    : 'border-blue-200'
                }`}
              >
                <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4">
                  <div className="flex items-start gap-3">
                    <div
                      className={`p-2.5 rounded-xl ${
                        isCritical
                          ? 'bg-red-50 text-red-600'
                          : isWarning
                          ? 'bg-amber-50 text-amber-600'
                          : 'bg-blue-50 text-blue-600'
                      }`}
                    >
                      <Icon className="w-5 h-5" />
                    </div>

                    <div>
                      <div className="flex items-center gap-2">
                        <span className="font-extrabold text-slate-900 text-sm">{alert.title}</span>
                        <Badge status={isCritical ? 'critical' : isWarning ? 'warning' : 'info'}>
                          {alert.severity}
                        </Badge>
                        {alert.acknowledged && (
                          <span className="text-[10px] font-bold px-2 py-0.5 rounded bg-slate-100 text-slate-600">
                            ACKNOWLEDGED
                          </span>
                        )}
                      </div>

                      <div className="text-xs text-slate-500 mt-0.5">
                        Location: <strong className="text-slate-700">{alert.location}</strong> • {alert.timestamp}
                      </div>

                      <p className="text-xs text-slate-600 mt-2 leading-relaxed">{alert.description}</p>

                      <div className="mt-3 p-3 rounded-lg bg-slate-50 border border-slate-100 text-xs text-slate-800">
                        <strong className="text-[#0b2545]">Recommended Action: </strong>
                        {alert.recommendedAction}
                      </div>
                    </div>
                  </div>

                  {/* Actions */}
                  <div className="flex sm:flex-col items-center sm:items-end gap-2 shrink-0">
                    {!alert.acknowledged && (
                      <Button
                        variant="outline"
                        size="sm"
                        icon={CheckCircle2}
                        onClick={() => handleAcknowledge(alert.id)}
                      >
                        Acknowledge
                      </Button>
                    )}
                    <Button
                      variant="ghost"
                      size="sm"
                      icon={Trash2}
                      className="text-slate-400 hover:text-red-600"
                      onClick={() => handleDismiss(alert.id)}
                    >
                      Dismiss
                    </Button>
                  </div>
                </div>
              </div>
            );
          })
        )}
      </div>
    </div>
  );
}
